# Dependencies
markdown:         kramdown
highlights:       true

# Permalinks
permalink:        pretty

# Setup
title:            HicksCTE
tagline:          'Business, Marketing, Technology'
class:			  'Configure class name in _config.yml'
description:      'A template for HicksCTE classroom discussions, activities.'
url:              http://hickscte.github.io/base/
baseurl:          

# Help
email:			  chicks@alpinedistrict.org
slack:

author:
  name:           'Caleb Hicks'
  url:            https://calebhicks.com

paginate:         1

# Custom vars
version:          .01

github:
  repo:           https://github.com/HicksCTE/base
